docs: update headless and stencil getting started guide into separate…
bigcommerce/b2b-buyer-portal pull request #144
Opened 2024-10-28 18:44 UTC by bc-micah

Jira: [DEVDOCS-5858](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5858)

## What/Why?
- Separate the headless and stencil guides to make it clearer and easier to understand.

## Rollout/Rollback
Revert

## Testing
N/A - Docs

[DEVDOCS-5858]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-28 19:11 UTC, bc-victor requested changes

2024-10-28 19:11 UTC, bc-victor commented on README.md
> +Read the [Stencil Guide](./docs/headless.md) when you are working on the BigCommerce Stencil storefront platform
```suggestion
Read the [Stencil Guide](./docs/stencil.md) when you are working on the BigCommerce Stencil storefront platform
```

2024-10-28 19:11 UTC, bc-victor commented on docs/stencil.md
> +      platform: 'headless',
```suggestion
      platform: 'bigcommerce',
```

2024-10-28 23:55 UTC, bc-marco requested changes
Please check the comments below

2024-10-28 23:55 UTC, bc-marco commented on docs/headless.md
> +      channel_id: { REPLACE_WITH_YOUR_CHANNEL_ID },
I think curly braces can cause confusion, so it should be better remove them
```suggestion
- Script for the `<body>` tag and make sure to replace the `REPLACE_WITH_YOUR_STORE_HASH` and `REPLACE_WITH_YOUR_CHANNEL_ID` with the appropriate information

```html
<script type="module" src="http://localhost:3001/src/main.ts"></script>
<script>
  window.B3 = {
    setting: {
      store_hash: 'REPLACE_WITH_YOUR_STORE_HASH',
      channel_id: REPLACE_WITH_YOUR_CHANNEL_ID,
```

2024-10-28 23:55 UTC, bc-marco commented on docs/headless.md
> +
Take advantage of markdown util
```suggestion
> [! WARNING]  
> Platform is required to load buyer portal properly, select one depending on [your store channel platform](https://developer.bigcommerce.com/docs/rest-management/channels#platform)
```

2024-10-28 23:55 UTC, bc-marco commented on docs/headless.md
> +      channel_id: '<YOUR_CHANNEL_ID>',
For consistency change this to
```suggestion
      store_hash: 'REPLACE_WITH_YOUR_STORE_HASH',
      channel_id: REPLACE_WITH_YOUR_CHANNEL_ID,
```

2024-10-28 23:55 UTC, bc-marco commented on docs/headless.md
> +- `<YOUR_CHANNEL_ID>` with the headless channel id
Also here
```suggestion
- `REPLACE_WITH_YOUR_STORE_HASH ` with your store hash
- `REPLACE_WITH_YOUR_CHANNEL_ID ` with the headless channel id
```

2024-10-28 23:55 UTC, bc-marco commented on docs/stencil.md
> +      channel_id: '<YOUR_CHANNEL_ID>',
As this is for stencil, it's okay to use
```suggestion
      store_hash: '{{settings.store_hash}}',
      channel_id: {{settings.channel_id}},
```

2024-10-28 23:55 UTC, bc-marco commented on docs/stencil.md
> +- `<YOUR_CHANNEL_ID>` with the headless channel id
This would not be required
```suggestion
```

2024-11-01 17:34 UTC, bc-marco approved these changes

2024-11-01 18:17 UTC, bc-victor approved these changes

2024-11-05 16:39 UTC, merged